include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_function_literals_in_foreach_calls: false
    avoid_relative_lib_imports: false

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
