name: tdd_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.3
  http: ^0.12.2
  mobx: ^1.2.1+4
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.11.1
  lint: ^1.3.0
  mobx_codegen: ^1.1.2
  mockito: ^4.1.3

flutter:
  uses-material-design: true
